"""
Equalizer Manager for Windows 11 Taskbar Widget
Integrates with Equalizer APO for real system-wide audio equalization
"""

import os
import logging
import subprocess
from pathlib import Path

class EqualizerManager:
    """Manages Equalizer APO configuration for system-wide audio EQ"""
    
    # Standard 10-band equalizer frequencies (Hz)
    BANDS = [31, 62, 125, 250, 500, 1000, 2000, 4000, 8000, 16000]
    
    # Preset configurations (band gains in dB, -12 to +12)
    PRESETS = {
        "Flat": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "Bass Boost": [8, 6, 4, 2, 0, 0, 0, 0, 0, 0],
        "Treble Boost": [0, 0, 0, 0, 0, 0, 2, 4, 6, 8],
        "Rock": [6, 4, 2, 0, -2, -1, 0, 2, 4, 6],
        "Pop": [0, 2, 4, 3, 0, -1, -2, 0, 2, 3],
        "Classical": [0, 0, 0, 0, 0, 0, -2, -2, -2, -4],
        "Jazz": [4, 3, 2, 0, -1, -1, 0, 2, 3, 4],
        "Electronic": [6, 4, 2, 0, -2, 2, 4, 4, 6, 8],
        "Vocal Boost": [0, 0, -2, -2, 4, 6, 4, 0, -2, -2],
        "Bass & Treble": [6, 4, 2, 0, -2, -2, 0, 2, 4, 6]
    }
    
    def __init__(self):
        self.apo_path = self.find_equalizer_apo()
        self.config_path = None
        if self.apo_path:
            self.config_path = self.apo_path / "config" / "config.txt"
            
    def find_equalizer_apo(self):
        """Locate Equalizer APO installation"""
        possible_paths = [
            Path(os.environ.get("ProgramFiles", "C:\\Program Files")) / "EqualizerAPO",
            Path(os.environ.get("ProgramFiles(x86)", "C:\\Program Files (x86)")) / "EqualizerAPO",
            Path("C:\\Program Files\\EqualizerAPO"),
        ]
        
        for path in possible_paths:
            if path.exists() and (path / "config").exists():
                logging.info(f"Found Equalizer APO at: {path}")
                return path
        
        logging.warning("Equalizer APO not found")
        return None
    
    def is_available(self):
        """Check if Equalizer APO is installed and accessible"""
        return self.apo_path is not None
    
    def get_current_settings(self):
        """Read current EQ settings from config file"""
        if not self.is_available():
            logging.warning("APO not available in get_current_settings")
            return [0] * 10
            
        try:
            # Create config file if it doesn't exist
            if not self.config_path.exists():
                logging.info("Config file doesn't exist, creating with flat EQ")
                self.config_path.parent.mkdir(parents=True, exist_ok=True)
                with open(self.config_path, 'w') as f:
                    f.write("# Generated by Taskbar Widget\n")
                    f.write("GraphicEQ: 31 0; 62 0; 125 0; 250 0; 500 0; 1000 0; 2000 0; 4000 0; 8000 0; 16000 0\n")
                return [0] * 10
            
            with open(self.config_path, 'r') as f:
                content = f.read()
                
            # Parse GraphicEQ line
            if "GraphicEQ:" in content:
                eq_line = [line for line in content.split('\n') if line.startswith("GraphicEQ:")][0]
                # Extract gains from format: GraphicEQ: 31 -6; 62 -4; ...
                gains = []
                parts = eq_line.replace("GraphicEQ:", "").strip().split(';')
                for part in parts:
                    if part.strip():
                        freq, gain = part.strip().split()
                        gains.append(float(gain))
                
                # Ensure we have exactly 10 bands
                if len(gains) == 10:
                    return gains
                else:
                    logging.warning(f"Expected 10 bands, got {len(gains)}")
                    return [0] * 10
        except Exception as e:
            logging.error(f"Error reading EQ settings: {e}")
            import traceback
            logging.error(traceback.format_exc())
        
        return [0] * 10  # Default flat
    
    def apply_preset(self, preset_name):
        """Apply a preset EQ configuration"""
        if preset_name not in self.PRESETS:
            logging.error(f"Unknown preset: {preset_name}")
            return False
            
        gains = self.PRESETS[preset_name]
        return self.apply_settings(gains)
    
    def apply_settings(self, gains):
        """Apply custom EQ settings (list of 10 gains in dB)"""
        if not self.is_available():
            logging.warning("Equalizer APO not available")
            return False
            
        if len(gains) != 10:
            logging.error(f"Expected 10 bands, got {len(gains)}")
            return False
            
        try:
            # Generate GraphicEQ line
            eq_parts = [f"{freq} {gain}" for freq, gain in zip(self.BANDS, gains)]
            eq_line = "GraphicEQ: " + "; ".join(eq_parts)
            
            # Read existing config
            if self.config_path.exists():
                with open(self.config_path, 'r') as f:
                    lines = f.readlines()
            else:
                lines = []
            
            # Replace or add GraphicEQ line
            new_lines = []
            found = False
            for line in lines:
                if line.startswith("GraphicEQ:"):
                    new_lines.append(eq_line + "\n")
                    found = True
                else:
                    new_lines.append(line)
            
            if not found:
                new_lines.append(eq_line + "\n")
            
            # Write back
            with open(self.config_path, 'w') as f:
                f.writelines(new_lines)
            
            logging.info(f"Applied EQ settings: {gains}")
            
            # Reload Equalizer APO config (if configurator exists)
            self.reload_config()
            return True
            
        except Exception as e:
            logging.error(f"Error applying EQ settings: {e}")
            return False
    
    def reload_config(self):
        """Trigger Equalizer APO to reload configuration"""
        try:
            # Try to find and run the configurator to reload
            configurator = self.apo_path / "Configurator.exe"
            if configurator.exists():
                # Just opening and closing triggers reload
                subprocess.Popen([str(configurator), "/reload"], 
                               creationflags=subprocess.CREATE_NO_WINDOW)
        except Exception as e:
            logging.debug(f"Could not reload config: {e}")
    
    def install_instructions(self):
        """Return installation instructions for Equalizer APO"""
        return """
Equalizer APO is not installed!

To enable real audio equalization:
1. Download Equalizer APO from: https://sourceforge.net/projects/equalizerapo/
2. Run the installer and select your audio device
3. Restart your computer
4. Restart this widget

Equalizer APO is free, open-source, and provides system-wide audio equalization.
"""
